### PR TITLE
Support directly including `htmlDependency()` objects in rmarkdown

### LINKED ISSUE #375: `runtime: shiny` in Rmarkdown doesn't know how to handle htmlDependency()
If an `htmltools::htmlDependency()` gets added to the UI of a regular shiny app, shiny knows how to treat it as a dependency and add the scripts/css files to the head.

If it gets added to a shiny-powered Rmarkdown, it gets converted to text. 

Example:

The following shiny app adds the fontawesome dependencies, and therefore the icon shows up

```r
library(shiny)

ui <- fluidPage(
  fontawesome::fa_html_dependency(),
  tags$i(class = "fas fa-pencil")
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

The following Rmarkdown treats the dependency as text

````r
---
runtime: shiny
---

```{r}
fontawesome::fa_html_dependency()
tags$i(class = "fas fa-pencil")
```
````

The rmarkdown version does work if I wrap the dependency in an empty `attachDependencies()`:

```r
htmltools::attachDependencies(HTML(''), fontawesome::fa_html_dependency())
```

This is technically not a bug because the documentation of `htmlDependency()` does say that these objects are meant to go inside `attachDependencies()`, but in practice because it works in regular shiny apps I would expect it to also work in Rmd.

### PR DESCRIPTION
**Pull request by gadenbuie**
This PR fixes #375, making it possible to include an `htmlDependency()` simply by calling it in an R chunk where it's handled by `knit_print()`.

Previously, users had to include the dependency in a `tagList()` or a `tag` to use the `knit_print.shiny.tag` method. Fortunately, that same method works for `htmlDependency()` objects too.

This small R Markdown document will now show the pencil icon, where previously it would print the font awesome dependency and no icon would be visible.

````markdown
---
title: Issue 375
---

```{r}
library(htmltools)

fontawesome::fa_html_dependency()
tags$i(class = "fas fa-pencil")
```


```{r}
print(fontawesome::fa_html_dependency())
```
````

This is a _slightly_ breaking change in the sense that users who were previously printing the html dependency will now need to use `print()` explicitly to show the object structure. In general, I think the new behavior is preferable.

### CODE REVIEW

**Review by schloerke — APPROVED** [review]

**Comment by gadenbuie** [comment]
@schloerke I added `skip_if_not_installed("knitr")` to the test I added around this change, should we ensure knitr is installed in CI for `r-cmd-check`? It currently isn't due to knitr being an Enhances dependency

**Comment by schloerke** [comment]
Good catch!

**Comment by schloerke** [comment]
Yes, let's add it in `Config/needs/check: knitr` in the DESCRIPTION file. (Similar to `Config/needs/website`)

**Review by cderv — APPROVED** [review]
LGTM too. I think this will be easier to use now. 

It seems like a justified breaking change to me.

**Pull request merged**
