### PR TITLE
Allow partial path in save_html #104

### LINKED ISSUE #104: save_html cannot work with relative path
Hi, I'm using the `save_html` function in one of my packages and a user discovered this bug: https://github.com/haozhu233/kableExtra/issues/220

It seems like we cannot use `save_html` with relative path. For example, if you do 
`save_html("aaa", "Desktop/aaa.html")`
it will generate an error.

### PR DESCRIPTION
**Pull request by haozhu233**
Fix #104

### CODE REVIEW

**Comment by haozhu233** [comment]
Any updates on this?

**Comment by cpsievert** [comment]
@haozhu233 if you could also provide some minimal examples/tests that demonstrate the fix, we'd be more likely to take this on, thanks!

**Review by yihui — APPROVED** [review]
@cpsievert I feel this is a pretty bad bug and we should definitely fix it. This PR is relatively simple, and I'd probably just merge it (after adding a NEWS item). That said, it's easy to create a minimal example that demonstrates the bug, so I just made one:

```r
owd = setwd(tempdir())
dir.create('foo')
htmltools::save_html(DT::datatable(iris), 'foo/bar.html')
setwd(owd)
```

This will throw an error.

**Comment by cpsievert** [comment]
Thank you for this nice contribution @haozhu233, and sorry for the delay! We'll take this over the finish line in #192

**Pull request closed without merging**
