### PR TITLE
v0.5.5 release candidate (#369)Co-authored-by: Yihui Xie <xie@yihui.name>

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by yihui** [comment]
If this release has not been made yet, could you ship 5ac897b with it? It's a simple change and should be fairly safe. Thanks!

**Comment by cpsievert** [comment]
Sure thing, does it seem worth adding a NEWS item for?

**Comment by yihui** [comment]
Right. It's just a trivial change.

**Comment by yihui** [comment]
Sorry I just realized that I missed another change and just added it. It seems you have not submitted to CRAN yet, and I hope you don't mind.

**Pull request merged**
