### PR TITLE
add functions: tagGetAttribute, tagHasAttribute; unittests: tagAppendAttributes

### PR DESCRIPTION
**Pull request by daattali**

### CODE REVIEW

**Comment by daattali** [comment]
I have some code pending on this PR; just wanted to ping this thread so that maybe someone will take a look soon if anyone has time. It's a very minimal addition to the code, most of the added lines are tests so it shouldn't take very long. Thanks!

**Comment by yihui** [comment]
LGTM.

**Comment by jjallaire** [comment]
@jcheng5 Does this look okay to you?

**Comment by jcheng5** [comment]
LGTM. I sent a CLA over email, once we get that filed I'll merge.

**Comment by daattali** [comment]
I'll send the form as soon as I get access to a printer

**Pull request merged**
