### PR TITLE
Allow dependencies to be merged when resolved

### PR DESCRIPTION
**Pull request by yihui**
Added a `mergeable` argument to `htmlDependency()`.

### CODE REVIEW

**Comment by jjallaire** [comment]
LGTM. @wch and @jcheng5 could you also take a look?

**Comment by wch** [comment]
Looks good to me.

**Comment by jcheng5** [comment]
@yihui Can you explain what this is for?

**Comment by yihui** [comment]
@jcheng5 Sure. Here is the motivation: https://github.com/rstudio/rmarkdown/issues/645 For example, when using the Buttons extension in DT, users may choose a subset of buttons, and different buttons require different JS modules: https://github.com/rstudio/DT/tree/master/inst/htmlwidgets/lib/datatables-extensions/Buttons/js Some modules are pretty big (e.g. the ones for exporting the table to PDF or Excel), so I do not want to include all scripts on the page. If you have two HTML dependencies that have the same name and version but different JS files, the second dependency will simply be dropped. So if I have two widgets that use different Buttons modules, the second widget will not render properly.

**Comment by jcheng5** [comment]
@yihui Can you make those distinct dependencies (with differing names)? That's the approach we've taken in Leaflet.

**Comment by yihui** [comment]
@jcheng5 I'm going to split the dependencies in DT into smaller units, so I'll close this PR for now, and please feel free to make a CRAN release with the current master branch. Thanks!

**Pull request closed without merging**
